apiVersion: v1
name: argo-cronjob
version: 1.0.0
description:  Argo Cronjob/CronWorkflow Helm Chart Template
keywords:
  - argo
  - cronjob
  - helm
home: https://github.com/acarter-ims/Helm-Charts
  - https://acarter-ims.github.io/Helm-Charts/argo-cronjob
maintainers:
  - name: Austin Carter
    email: acarter@wakkalabs.com